export const DEFAULT_THEME = {
  light: {
    "--color-primary": "#1e82ca",
    "--color-primary-content": "#ffffff",
    "--color-secondary": "#f0f0f0",
    "--color-secondary-content": "#000000",
    "--color-accent": "#1e82ca",
    "--color-accent-content": "#ffffff",
    "--color-neutral": "#0a0a1f",
    "--color-neutral-content": "#ffffff",
    "--color-base-100": "#f8f9fa",
    "--color-base-200": "#ffffff",
    "--color-base-300": "#96bee9",
    "--color-base-content": "#1f2937",
    "--color-info": "#01b3cb",
    "--color-info-content": "#ffffff",
    "--color-success": "#00d181",
    "--color-success-content": "#ffffff",
    "--color-warning": "#ffb700",
    "--color-warning-content": "#ffffff",
    "--color-error": "#e82f21",
    "--color-error-content": "#ffffff",
  },
  dark: {
    "--color-primary": "#1e82ca",
    "--color-primary-content": "#001a1f",
    "--color-secondary": "#cfcfcf",
    "--color-secondary-content": "#ffffff",
    "--color-accent": "#1e82ca",
    "--color-accent-content": "#ffffff",
    "--color-neutral": "#0a0a1f",
    "--color-neutral-content": "#fefbf6",
    "--color-base-100": "#050510",
    "--color-base-200": "#242447",
    "--color-base-300": "#196194",
    "--color-base-content": "#ffffff",
    "--color-info": "#01b3cb",
    "--color-info-content": "#ffffff",
    "--color-success": "#00d181",
    "--color-success-content": "#ffffff",
    "--color-warning": "#ffb700",
    "--color-warning-content": "#ffffff",
    "--color-error": "#e82f21",
    "--color-error-content": "#ffffff",
  },
}
